### ISSUE TITLE
方法实现不小心搞错了。

### ISSUE THREAD

**Issue by zhhaojie** [yingzhuo/spring-turbo#165]
spring.turbo.util.BigDecimalUtils#max(java.math.BigDecimal...)

**Comment by yingzhuo** [comment]
@zhhaojie 谢谢您。 此bug已经在 2.0.5-SNAPSHOT 中修复。

**Comment by yingzhuo** [comment]
如下两个版本已发布

`1.3.2`
`2.0.5`

此bug已解决。
